# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yoIj4EVVE_8jXIPLRUEmqfkYrPTXTUVL
"""

import pandas as pd
import matplotlib.pyplot as plt

df= pd.read_csv("/content/2- share-of-global-plastic-waste-emitted-to-the-ocean.csv")
df2= pd.read_csv("/content/1- global-plastics-production.csv")
df3= pd.read_csv("/content/3- share-plastic-fate.csv")
df4= pd.read_csv("/content/4- mismanaged-plastic-waste-per-capita.csv")

df.head(100)

df.isnull().sum()

df.drop_duplicates()

df.isnull().sum()

df["Code"]= df["Code"].fillna("NAN")

df2.head()

df2.isnull().sum()

df3

df =df.replace("uknown","unknown")

df3.isnull().sum()

df3["Code"]= df["Code"].fillna("uknown")

df4["Code"] = df4["Code"].fillna("unknown")

df.describe()

plt.figure(figsize=(15, 10))

plt.subplot(1,2,1)
df2.groupby("Year")['Annual plastic production between 1950 and 2019'].sum().sort_values(ascending=False).plot(color = "Green",linestyle ="-", marker = ".")
plt.title("Plastic Productions Yearly Trends")
plt.xlabel("Year")
plt.ylabel("Production in Tonnes")
plt.grid(True)

plt.subplot(1,2,2)
df[df['Entity']!='Asia'].groupby('Entity')['Share of global plastics emitted to ocean'].sum().sort_values(ascending=False).head(5).plot(kind ='barh',color ="green" )
plt.xlabel("Share of Global Plastics Emitted to Ocean")
plt.title("Top 5 Plastic Emitting Countries")
plt.ylabel("Country")


plt.show()



plt.figure(figsize=(10,5))
plt.subplot(1,2,1)
df3.groupby ('Entity')['Share of waste incinerated from total regional waste'].sum().sort_values(ascending=True).round(2).head(10).plot(kind= 'barh' )
plt.title("Share of  Waste Incinerated  By Country ")
plt.xlabel ( 'share of  waste incinerated')
plt.ylabel( 'country')


plt.subplot(1,2,2)
df3.groupby ('Entity')['Share of waste recycled from total regional waste'].sum().sort_values(ascending=True).round(2).head(10).plot(kind= 'barh' )
plt.title("Share of  Waste Recycled  By Country ")
plt.tight_layout()
plt.xlabel ( 'share of  waste recycled')
plt.ylabel( 'country')
plt.show()

df[df['Entity']!='Asia'].groupby('Entity')['Share of global plastics emitted to ocean'].sum() .sort_values(ascending=False).head(5).plot(kind ='barh',color ="green" )
plt.xlabel("country")
plt.title("plastic emitt by countries ")
plt.ylabel("share of global plastics emitted to ocean")
plt.show()

plot_data = df3.groupby('Year')['Share of waste recycled from total regional waste'].min().round(1).reset_index()
plot_data.plot(kind = 'scatter', x='Year', y= 'Share of waste recycled from total regional waste', color='Red')

df3

plt.figure(figsize=(12,6))

df3[df3['Entity']!='World'].groupby('Year')['Share of waste landfilled from total regional waste'].sum().plot(kind='line', marker='o')
plt.title('Total Share of Waste Landfilled Over Years (Excluding World)')
plt.xlabel('Year')
plt.ylabel('Total Share of Waste Landfilled')
plt.grid(True)
plt.tight_layout()
plt.show()

df.to_csv("cleaned share")

df2.to_csv("cleaned global production")

df3.to_csv("cleaned share plastic fate")

df4.to_csv("cleaned mismanaged")